modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="immersiverailroading"
version="${file.jarVersion}"
displayName="Immersive Railroading"

[[dependencies.immersiverailroading]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverailroading]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverailroading]]
    modId="trackapi"
    mandatory=true
    versionRange="[1.1,)"
    ordering="BEFORE"
    side="BOTH"


[[dependencies.immersiverailroading]]
    modId="universalmodcore"
    mandatory=true
    versionRange="[1.2, 1.3)"
    ordering="BEFORE"
    side="BOTH"
